server:
  port: 8013

spring:
  application:
    name: multi-tenant
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sevenhallo?ApplicationName=multi-tenant'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
